apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
        tier: backend
    spec:
      containers:
      - name: auth
        image: 192.168.147.11:5000/spring-boot-docker-k8s-auth
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 25001